// boilerplate/vue/page/home/home.vue
<template>
  <Layout description="vue server side render" keywords="egg, vue, webpack, server side render">
    <div class="container smart-container">
      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <ul class="smart-artiles" id="articleList">
            <li v-for="item in lists" :key="item.id">
              <div class="point">+{{item.hits}}</div>
              <div class="card">
                <h2><a :href="item.url" target="_blank">{{item.title}}</a></h2>
                <div>
                  <ul class="actions">
                    <li>
                      <time class="timeago">{{item.moduleName}}</time>
                    </li>
                    <li class="tauthor">
                      <a href="#" target="_blank" class="get">Sky</a>
                    </li>
                    <li><a>+收藏</a></li>
                    <li>
                      <span class="timeago">{{item.summary}}</span>
                    </li>
                    <li>
                      <span class="timeago"></span>
                    </li>
                  </ul>
                </div>
              </div>
            </li>
          </ul>
          <div id="pagerBottom" class="smart-pager" v-if="isLoading">
            <image src="../../asset/images/loading.gif"></image>
          </div>
        </div>
      </div>
    </div>
  </Layout>
</template>
<style>
  @import "home.css";
</style>
<script type="text/babel">
  import Article from 'mocks/article/list';
  export default {
    components: {

    },
    data(){
      return {
        isFinish: false,
        isLoading : false,
        pageIndex: 1,
        pageSize: 10,
        list: []
      }
    },
    computed: {
      lists(){
        return this.list;
      }
    },
    methods: {
      fetch(){
        Promise.resolve(Article.getPage(this.pageIndex, this.pageSize)).then(res=> {
        //this.$http.get(`/pager?pageIndex=${this.pageIndex}&pageSize=${this.pageSize}`).then(res=> {
          console.log('res', res);
          if(res.list && res.list.length){
            this.total = res.total;
            this.list = this.list.concat(res.list);
          }else{
            this.isFinish = true;
          }
          this.isLoading = false;
        });
      },
      loadPage(){
        if (!this.isFinish && !this.isLoading) {
          this.isLoading = true;
          this.pageIndex++;
          setTimeout(()=>{
            this.fetch();
          }, 1500);
        }
      }
    },
    mounted() {
      this.loadPage();
      window.addEventListener('scroll', ()=>{
        this.loadPage();
      }, false);
    }
  }
</script>

// boilerplate/react-antd/src/router/component/home.jsx
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { list, add, del } from '../../store/actions';
import './home.css';
class Home extends Component {

  render() {
    const { add, del, list } = this.props;
    const id = list.length + 1;
    const item = {
      id,
      title: `React + Redux + React-Router + AntD 单页面实现-${id}`,
      summary: '基于 React + easywebpack 工程骨架项目',
      hits: 550 + id,
      url: 'https://github.com/hubcarl/egg-react-webpack-boilerplate'
    };
    return <div className="redux-nav-item">
      <div className="container">
        <h1>React + Redux + React-Router + AntD</h1>
        <ul className="smart-artiles" id="articleList">
          {list.map(function(item) {
            return <li key={item.id}>
              <div className="point">+{item.hits}</div>
              <div className="card">
                <h2><a href={item.url} target="_blank">{item.title}</a></h2>
                <div>
                  <ul className="actions">
                    <li>
                      <time className="timeago">{item.moduleName}</time>
                    </li>
                    <li className="tauthor">
                      <a href="#" target="_blank" className="get">Sky</a>
                    </li>
                    <li><a>+收藏</a></li>
                    <li>
                      <span className="timeago">{item.summary}</span>
                    </li>
                    <li>
                      <span className="redux-btn-del" onClick={() => del(item.id)}>Delete</span>
                    </li>
                  </ul>
                </div>
              </div>
            </li>;
          })}
        </ul>
      </div>
      <div className="redux-btn-add" onClick={() => add(item)}>Add</div>
    </div>;
  }
}


const mapStateToProps = state => {
  return {
    list: state.list
  };
};

export default connect(mapStateToProps, { add, del })(Home);
