// boilerplate/vue3/src/component/header/header.vue
<template>
  <header class="header">
    <div class="container"><h1>
      <a href="#" class="router-link-active">Vue App</a></h1>
      <ul class="nav">
        <li class="nav-item"><a href="https://github.com/easy-team">GitHub</a></li>
      </ul>
    </div>
  </header>
</template>
<style>
  @import "./header.css";
</style>
<script type="text/babel">
  export default{
    data(){
      return {
        selectedMenu : '/app'
      }
    },
    computed:{

    },
    mounted(){
      this.selectedMenu = window.location.pathname.toLowerCase().replace(/\/$/,'');
    }
  }
</script>

// boilerplate/react-typescript/src/component/header/index.tsx
import React, { Component } from 'react';
import './index.css';
export default class Header extends Component {
  render() {
    return <header className="header">
      <div className="container"><h1>
        <a href="/" className="router-link-active">React + TypeScript</a></h1>
      </div>
    </header>;
  }
}
